# Generated by Django 3.2.3 on 2021-05-30 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gdapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'username', 'verbose_name_plural': 'usersname'},
        ),
    ]
