# Generated by Django 3.2.3 on 2021-05-30 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gdapp', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
