# Generated by Django 3.2.7 on 2021-10-03 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gdapp', '0004_auto_20210530_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communicatewithpeople',
            options={},
        ),
        migrations.AlterModelOptions(
            name='diary',
            options={},
        ),
        migrations.AlterModelOptions(
            name='drugnotification',
            options={},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={},
        ),
    ]
